# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 22d6bc1648afaa1f87c39e922494edbeb93e6e86771225eca6904ab3b1f3f4789ab13a3f24f9a3177c470a2cce82b2b209812c03d826cb845b0015b631fe3bf6

test:
  secret_key_base: 596b64c3d46a2b9e29536f945f3ad5e0f57cb9a5dceb5ae4330bfb7c305beea9d420745e73ca2cc553ea2ec032826c4ffc48764747f8a07bb27a34e57c2101a2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
